import React from 'react';

export default function Home() {
  return (
    <main className="min-h-screen bg-white py-12 px-6 text-slate-900">
      <div className="max-w-4xl mx-auto space-y-12">
        {/* Header Section */}
        <header className="border-b border-slate-200 pb-8 text-left">
          <h1 className="text-3xl font-bold mb-4 tracking-tight">Yuhsaku Nakai</h1>
          <div className="flex flex-wrap gap-x-8 gap-y-2 text-slate-600 text-sm">
            <div className="flex items-center gap-2">
              <span className="font-semibold text-slate-900">GitHub:</span>
              <a href="https://github.com/aliks-kuro" target="_blank" rel="noopener noreferrer" className="hover:underline text-blue-600">github.com/aliks-kuro</a>
            </div>
            <div className="flex items-center gap-2">
              <span className="font-semibold text-slate-900">Email:</span>
              <span>your-email@example.com</span>
            </div>
          </div>
        </header>

        {/* Education Section */}
        <section>
          <h2 className="text-xl font-bold mb-6 text-slate-900 uppercase tracking-wider border-l-4 border-slate-900 pl-3">Education</h2>
          <div className="space-y-6">
            <div>
              <div className="flex justify-between items-baseline">
                <p className="font-bold text-lg">青山学院大学大学院 理工学研究科 理工学専攻</p>
                <p className="text-sm text-slate-500">2026.04 - 入学予定</p>
              </div>
              <p className="text-slate-700">知能情報コース 実世界通信研究室</p>
            </div>
            <div>
              <div className="flex justify-between items-baseline">
                <p className="font-bold text-lg">青山学院大学 理工学部 情報テクノロジー学科</p>
                <p className="text-sm text-slate-500">2022.04 - 2026.03</p>
              </div>
              <p className="text-slate-700">卒業予定</p>
            </div>
            <div className="mt-4 p-4 bg-slate-50 border border-slate-200 text-sm">
              <span className="font-bold">Future Plan:</span> フランス ジャン・モネ大学へ1年間の留学を予定。
            </div>
          </div>
        </section>

        {/* Research & Conferences */}
        <section>
          <h2 className="text-xl font-bold mb-6 text-slate-900 uppercase tracking-wider border-l-4 border-slate-900 pl-3">Research & Conferences</h2>
          <div className="space-y-8">
            <div>
              <p className="text-xs font-bold text-slate-500 mb-1">IEEE / Poster Presentation (2025)</p>
              <h3 className="text-lg font-bold mb-1">The 2025 IEEE International Conference on Consumer Electronics (ICCE)</h3>
              <p className="text-slate-700 italic">"Control of Battery Usage in Smartphones Based on a Regression Model"</p>
            </div>

            <div>
              <p className="text-xs font-bold text-slate-500 mb-1">Current Research (2026)</p>
              <h3 className="text-lg font-bold mb-1">Domain Heuristic Mixer (DHM-QAOA)</h3>
              <p className="text-slate-700 leading-relaxed">
                ドメイン知識を活用した動的ヒューリスティック・ミキサーの導入による、量子アルゴリズムを用いたゲームマッチングの最適化
              </p>
            </div>
          </div>
        </section>

        {/* Awards Section */}
        <section>
          <h2 className="text-xl font-bold mb-6 text-slate-900 uppercase tracking-wider border-l-4 border-slate-900 pl-3">Awards</h2>
          <div className="flex justify-between items-start border-b border-slate-100 pb-4">
            <div>
              <p className="font-bold text-lg">名証株式投資コンテスト 団体戦 優勝</p>
            </div>
            <p className="text-sm text-slate-500 font-bold">2025.12</p>
          </div>
        </section>

        {/* Footer */}
        <footer className="text-center text-slate-400 text-xs py-10 border-t border-slate-100">
          <p>&copy; 2026 あなたの名前 - Generated by Next.js & Vercel</p>
        </footer>
      </div>
    </main>
  );
}